### ISSUE TITLE
infinite recusrion on calc_times_case_2

### ISSUE THREAD

**Issue by enomado** [marcbone/s_curve#3]
here is my data to reproduce:
```
 let constraints = SCurveConstraints {
        max_jerk: 3000.,
        max_acceleration: 2600.,
        max_velocity: 600.0,
    };
    let start_conditions = SCurveStartConditions {
        q0: 0.,  
        q1: 1,
        v0: 12.,
        v1: 12.,
    };
```

**Comment by marcbone** [comment]
On my machine, it converges after 377 iterations. I guess your stack size on whatever you are running is not big enough.
I published a new version with an improved iteration algorithm solving your specific problem with 39 iterations.

**Comment by enomado** [comment]
Awesome. I would have had enough simple panic or Result type
