### ISSUE TITLE
another bad results and bad params

### ISSUE THREAD

**Issue by enomado** [marcbone/s_curve#5]
Hi. this time its for negative position. params like:
```
    let constraints = SCurveConstraints {
        max_jerk: 240000.,
        max_acceleration: 260000.,
        max_velocity: 65600.0,
    };
    let start_conditions = SCurveStartConditions {
        q0: 0.,           // start position
        q1: -6400*10, // end position
        v0: 0.,           // start velocity
        v1: 0.,           // end velocity
    };
    ```
    
    
![Screenshot_2021-08-21_04-10-22](https://user-images.githubusercontent.com/707007/130305827-3f58fc24-d0df-4ae3-aeb0-f4098498f33e.png)

Its okay if it is not good params, but I guess if will help. thank you

**Comment by r2k-in-the-vortex** [comment]
reverse move had number of difficulties, I think my changes ( https://github.com/marcbone/s_curve/pull/7 ) also address your issue, but I'm not sure, because -6400*10 is not a f64, it's a compile error

**Comment by marcbone** [comment]
I guess this issue is fixed with the latest release. Feel free to reopen if you still experience this issue
